# Change these first
owner: MatadorProBr # Your GitHub organization or username, where this repository lives
repo: BetterCrewLink-status # The name of this repository

sites:
  - name: BetterCrewLink Voice Server
    url: https://bettercrewl.ink
  - name: BetterCrewLink Web
    url: https://web.bettercrewl.ink
  - name: BetterCrewLink OBS Overlay
    url: https://obs.bettercrewlink.app
  - name: BetterCrewLink Short URL
    url: https://bettercrewlink.app

assignees: # Users to assign downtime issues
  - OhMyGuus

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /BetterCrewLink-status
  logoUrl: https://github.com/OhMyGuus/BetterCrewLink/raw/nightly/src/renderer/logos/sizes/256-BCL-Logo-shadow.png
  name: BetterCrewLink Status
  introTitle: "BetterCrewLink's status site for our services"
  introMessage: A status site for our services, some important and mod-needed (the BetterCrewLink Voice Server, Web and OBS Overlay) and some vanity / non-important (the Short URL)
  theme: dark
  navbar:
    - title: Status
      href: /BetterCrewLink-status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
