# Change these first
owner: MatadorProBr # Your GitHub organization or username, where this repository lives
repo: BetterCrewLink-status # The name of this repository

sites:
  - name: Voice Server
    url: https://bettercrewl.ink/
    icon: https://raw.githubusercontent.com/OhMyGuus/BetterCrewLink/nightly/src/renderer/logos/BCL-Logo-shadow.svg
  - name: Web Version
    url: https://web.bettercrewl.ink/
    icon: https://raw.githubusercontent.com/OhMyGuus/BetterCrewlink-mobile/master/src/assets/icon/favicon.png
  - name: Offsets (GitHub)
    url: https://api.github.com/repos/OhMyGuus/BetterCrewlink-Offsets
  - name: Updater (GitHub)
    url: https://api.github.com/repos/OhMyGuus/BetterCrewLink/releases
  - name: Hats (GitHub)
    url: https://api.github.com/repos/OhMyGuus/BetterCrewLink-Hats
  - name: OBS Overlay
    url: https://obs.bettercrewlink.app/
    icon: https://raw.githubusercontent.com/ottomated/CrewLink/master/resources/icon.png
  - name: Mirror
    url: https://mirror.bettercrewl.ink/
  - name: GitHub Release Redirector
    url: https://bettercrewlink.app/
    icon: https://cdn-icons-png.flaticon.com/512/25/25231.png

assignees:
  - OhMyGuus

status-website:
  cname: bettercrewlink-status.netlify.app
  theme: night
  logoUrl: https://github.com/OhMyGuus/BetterCrewLink/raw/nightly/src/renderer/logos/BCL-AppIcon.png
  favicon: https://github.com/OhMyGuus/BetterCrewLink/raw/nightly/src/renderer/logos/BCL-AppIcon.png
  faviconSvg: https://github.com/OhMyGuus/BetterCrewLink/raw/nightly/src/renderer/logos/BCL-AppIcon.svg
  name: BetterCrewLink Status
  introTitle: "[BetterCrewLink](https://github.com/OhMyGuus/BetterCrewLink) status site for our services"
  introMessage: A status site for our services, some important and mod-needed ([Voice Server](/history/voice-server), [Web](/history/web-version), [Offsets](/history/offsets-git-hub), [Updater](/history/updater-git-hub), [Hats](/history/hats-git-hub), [OBS Overlay](/history/obs-overlay) and [Mirror](/history/mirror)) and some vanity / non-important ([GitHub Release Redirector](/history/git-hub-release-redirector))
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: BetterCrewLink GitHub
      href: https://github.com/OhMyGuus/BetterCrewLink

notification:
  - type: discord

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

i18n:
  footer: Made with ❤️ by [MatadorProBr](https://github.com/MatadorProBr) and [BetterCrewLink](https://github.com/OhMyGuus/BetterCrewLink), 🔌 by [Upptime](https://github.com/upptime/upptime).

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
